### ISSUE TITLE
endly -s=docker:run errors

### ISSUE THREAD

**Issue by rzhaovi** [viant/endly#54]
```
$ endly -s=docker:run
ServiceRequest: ...
```
...
```
YAML request:
panic: Duplicated key 'name' in struct docker.RunRequest [recovered]
	panic: Duplicated key 'name' in struct docker.RunRequest

goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc000f65918)
	/Users/awitas/go/src/gopkg.in/yaml.v2/yaml.go:249 +0x9a
panic(0x3f72e40, 0xc0014b2cd0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
gopkg.in/yaml%2ev2.(*encoder).structv(0xc0004202c0, 0x0, 0x0, 0x4567220, 0xc0011957a0, 0x199)
	/Users/awitas/go/src/gopkg.in/yaml.v2/encode.go:211 +0x118
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0004202c0, 0x0, 0x0, 0x4567220, 0xc0011957a0, 0x199)
	/Users/awitas/go/src/gopkg.in/yaml.v2/encode.go:160 +0x767
gopkg.in/yaml%2ev2.(*encoder).marshal(0xc0004202c0, 0x0, 0x0, 0x40b24c0, 0xc0011957a0, 0x16)
	/Users/awitas/go/src/gopkg.in/yaml.v2/encode.go:154 +0x5e0
gopkg.in/yaml%2ev2.(*encoder).marshalDoc(0xc0004202c0, 0x0, 0x0, 0x40b24c0, 0xc0011957a0, 0x16)
	/Users/awitas/go/src/gopkg.in/yaml.v2/encode.go:93 +0x10f
gopkg.in/yaml%2ev2.Marshal(0x40b24c0, 0xc0011957a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/awitas/go/src/gopkg.in/yaml.v2/yaml.go:203 +0x329
github.com/viant/endly/bootstrap.printServiceActionInfo(0xc000f65b58, 0xc0014498c0, 0x46aaf42, 0x4, 0x46b0810, 0x7, 0x40b24c0, 0xc0011957a0)
	/Users/awitas/go/src/github.com/viant/endly/bootstrap/bootstrap.go:515 +0x957
github.com/viant/endly/bootstrap.printServiceActionRequest()
	/Users/awitas/go/src/github.com/viant/endly/bootstrap/bootstrap.go:554 +0x3e0
github.com/viant/endly/bootstrap.printServiceActions()
	/Users/awitas/go/src/github.com/viant/endly/bootstrap/bootstrap.go:571 +0x8e0
github.com/viant/endly/bootstrap.Bootstrap()
	/Users/awitas/go/src/github.com/viant/endly/bootstrap/bootstrap.go:239 +0xbfa
main.main()
	/Projects/go/workspace/src/github.com/viant/endly/endly/endly.go:6 +0x20
```

**Comment by adranwit** [comment]
patched in master
